require 'active_record'
include ActiveRecord::Tasks

DatabaseTasks.db_dir = 'db'
DatabaseTasks.migrations_paths = ['db/migrate']
load 'active_record/railties/databases.rake'

task :environment do
  puts "Totally loading the environmet bruh"
  ActiveRecord::Base.establish_connection(adapter: "sqlite3", database:"db/school.db")
end
